[package]
name = "vargds-core"
version = "0.1.0"
edition = "2021"

[features]
log = []
default = ["log"]

[dependencies]
slog = "2.7.0"

[dependencies.arm-decode]
path = "../arm-decode"

[build-dependencies]
arm-decode = {path = "../arm-decode"}